### ISSUE TITLE
非常棒! 但是想知道这个库有没有被任何一款用户量较大的App充分验证过?

### ISSUE THREAD

**Issue by matrixxun** [baiiu/DropDownMenu#1]
如题!
谢谢!

**Comment by baiiu** [comment]
@matrixxun 哈哈哈，我们公司就用的这个，目前没有问题。另外我知道因为需求会大不一样，导致筛选器会的样式会很不一样。所以我就没有添加 gradle dependencies，你可以根据需求改代码。

**Comment by matrixxun** [comment]
你们这个android 客户端产品大概有多少日活?

**Comment by baiiu** [comment]
@matrixxun  谢谢你提Issue，代码质量是需要被验证的，一般来说，代码越清晰，代码质量越高，就越不容易出错。没有人能保证自己写的代码是完全无错的吧，都是迭代出来的。如果你在使用过程中发现有什么错误，可以再次提Issue，我再修改完善。
另外这个筛选器，个人觉得写的不错，确实抽出来了，复用性很强，但是star少，所以目前应该只被很少人采纳。
恩，谢谢你能这么问，让我以后可以更关注代码的安全性。嘿嘿。
