### ISSUE TITLE
菜单中的item点击后无法知道是那个选项里的

### ISSUE THREAD

**Issue by 3440395** [baiiu/DropDownMenu#10]
当有多个选项用的同一种view的时候（第一个和第二个都是doublelistview） 点doublelistview里面的item 是否可以知道是那个选项卡的   没有找到类似的信息 ，如果有的话，麻烦告知一下。 我现在是议在doublielistview，SingleListView等加入一个 position的属性，然后通过set方法设置他是属于哪个选项卡，然后再onItemClick中传入 正好用到了这个需求。如果已经有了这个功能 ，教我一下，谢谢

**Comment by baiiu** [comment]
恩，是的，没有。在项目的demo里手动给FilterUrl设置position和positionString的。
