### ISSUE TITLE
BetterDoubleGridView

### ISSUE THREAD

**Issue by eppen** [baiiu/DropDownMenu#12]
BetterDoubleGridView 上下两个list
如果碰巧两个list里面有部分值相同，
那么就只能选中一个。

**Comment by baiiu** [comment]
@eppen 
恩，在Sample中的两个GridView并不是Lib，因为各家对于这种样式的都不一样。所以就放在Sample中了。后期会写一个基于RecyclerView的适用更多场景的Grid筛选器。
