### ISSUE TITLE
想问下当有多个 SingleListView 选择器的时候

### ISSUE THREAD

**Issue by initzf** [baiiu/DropDownMenu#17]
想问下当有多个 SingleListView 选择器的时候 ,不论选择那个 ，都只会改变第一个选择器的title ，这个有什么好的办法做优化吗？

**Comment by baiiu** [comment]
看源码啦，在FilterUrl中控制。我封装的只是UI方面，对数据还要自己处理。

**Comment by initzf** [comment]
嗯，已经解决了这个问题了，谢谢，这个库非常的棒。

**Comment by baiiu** [comment]
恩，谢谢谢谢。
