### ISSUE TITLE
双listview问题

### ISSUE THREAD

**Issue by liuzq8769** [baiiu/DropDownMenu#19]
第一次选择LeftListView中第0项，RightListView中第2项，加载出数据menu关闭没毛病。那么问题来了，当再一次打开menu选择LeftListView中第1项，RightListView中不选择，关闭menu，然后又打开menu，请问此时LeftListViewx中选择的是第？？？？项

**Comment by baiiu** [comment]
我封装的是UI，数据逻辑自己处理吧~，看下代码，很简单的封装而已。
