### ISSUE TITLE
由选中某个子项后，其他父项归位的想法引起的建议

### ISSUE THREAD

**Issue by Lianging** [baiiu/DropDownMenu#2]
你好，项目写得很好，受教了，我是有少少经验的开发者，以下是我使用后的一点点建议：
我的app中，使用的情况是作为单选，那么我选中其中一个子项后，之前有过选择的父项应该恢复成默认的状态，我查看了源码，好像没有这样的方法（可能是我看漏了），我只想到下面的方法：
用

> DropDownMenu.[setPositionIndicatorText](https://github.com/baiiu/DropDownMenu/blob/master/filter-lib/src/main/java/com/baiiu/filter/DropDownMenu.java)(int position, String text);
但是如果这样做的话要用到的position是上一次tab选中的标识，而我有找到了你的
> [FixedTabIndicator.getLastIndicatorPosition();](https://github.com/baiiu/DropDownMenu/blob/master/filter-lib/src/main/java/com/baiiu/filter/view/FixedTabIndicator.java)
调用这个方法，可以返回上一次tab点击的position，但是我发现返回来的position是点击时tab的position

好吧，我的思路是：
1、用户点击tab，在子项中选择某一个项（点击事件）
2、上次选择的父项恢复默认状态(注)，新选择的父项状态变为已选
**[(注)：这个时候应该调用getLastIndicatorPosition()，但是在（点击事件）FixedTabIndicator.switchTab(position)方法中，mLastIndicatorPosition已经被赋值为新的position了，所以getLastIndicatorPosition()得到的值也只是新的tab选择项而不是上一次选中的项。**

最后，我通过在switchTab(position)中，在赋值给mLastIndicatorPosition之前，把mLastIndicatorPosition缓存了，然后getLastIndicatorPosition中返回的是我刚刚缓存的值才解决了我的需要

写得有点多，描述可能不好，其实就是想作为单选，选中子项后，父项复位而已。

**Comment by baiiu** [comment]
你指的父项是FixTabIndicator里的内容么？你的意思是 选中一个筛选条件，其他的筛选条件全部恢复成默认的么?
如果我理解的没错的话，你可以这样做：

```
//1. 设置该position的text为你想要的
dropDownMenu.setPositionIndicatorText(position,wantedText),

//2. 复位FilterUrl里的url
FilterUrl.instance()....

```

这样应该就能实现单选了。
另外你可以在FilterUrl里提供一个reset()方法，把所有url复位，然后再选中时再设置url。这样会方便很多。Hope it can work.

**Comment by Lianging** [comment]
@baiiu 是的
