### ISSUE TITLE
recycleview滑动导致item的状态没有保存，holder的复用问题

### ISSUE THREAD

**Issue by cyiwon** [baiiu/DropDownMenu#20]
第4个dropdownmenu数据进行翻页会导致item状态改变，求修复。找到原因了，却不能很好的在项目中进行修改。烦请大神给修复下，先谢过了。

**Comment by baiiu** [comment]
第四个，指DoubleListView么。
对筛选器，我抽出来的是UI，在lib中，对于DoubleListView我并没有抽出来，只是放了个写法在app目录中。
对于adapter你可以填充任意View，数据需要自己处理。
