### ISSUE TITLE
在Fragment里如何使用

### ISSUE THREAD

**Issue by liuhui313364809** [baiiu/DropDownMenu#21]
谢谢你的例子很好用。不过我想把此项目放到Fragment 中不好用。
用到这个((AppCompatActivity) this.getActivity()).setSupportActionBar(toolbar);。但是好像必须把FragmentActivity 改成AppCompatActivity，如果改成了这样 会出现空指针异常，错误在这个地方dropDownMenu.setMenuAdapter(new DropMenuAdapter(this.getActivity(), titleList, this));

网上找了别的例子 还有((AppCompatActivity) this.getActivity()).setSupportActionBar(toolbar);  这个话改成toolbar.inflateMenu(R.menu.menu_message);。但是 你项目里好像没有 这个menu。求指教怎么在Fragment调用

**Comment by baiiu** [comment]
MenuAdapter传入的是Context，不是Activity啊。

另外在Fragment里使用menu时要设置setHasOptionsMenu(true);

**Comment by liuhui313364809** [comment]
你好，可以加qq 请求请教下吗？我设置了 你说的setHasOptionsMenu(true); 但是也不好用。请问老师 你有没有 把这个 筛选放到Fragment里面的 实例啊。想借鉴下 谢谢

**Comment by baiiu** [comment]
额，兄弟，互相学习，别这样。

我抽出来的是UI框架，和放在哪都没关系，就像PullToRefresh一样。
你过一遍源码，写的很简单的，是组合控件，都是很基本的技术，我都觉得挺渣的。然后就像使用上拉刷新一样就行了，在xml里包裹一下，就OK了。
