### ISSUE TITLE
请问下面的如果是个ListView如何实现下拉刷新或者上拉加载呢？

### ISSUE THREAD

**Issue by coolhorsema** [baiiu/DropDownMenu#27]

**Comment by baiiu** [comment]
一样的，不影响。

**Comment by coolhorsema** [comment]
首先，感谢您的回复。

但我还是想补充下
1、我使用的是PullToRefresh控件（com.jwenfeng.library.pulltorefresh.PullToRefreshLayout）包裹的ListView，他们两个在被DropDownMenu包裹，我怎么试都没有效果，请您指教
2、如果我改用RecyclerView呢

不吝赐教！



祝好！
-------------------------
coolhorsema@foxmail.com
 
发件人： Zhe Zhu
发送时间： 2017-11-16 19:26
收件人： baiiu/DropDownMenu
抄送： HowardMa; Author
主题： Re: [baiiu/DropDownMenu] 请问下面的如果是个ListView如何实现下拉刷新或者上拉加载呢？ (#27)
一样的，不影响。

**Comment by baiiu** [comment]
@coolhorsema 恩，刚看到。
DropDownMenu是一个ViewGroup，里面可以包括任何东西。
Demo中包裹的是一个TextView，你可以直接修改Demo，将TextView改为PullToRefreshLayout试下，之后再将PullToRefreshLayout里改成ListView或RecyclerView。
最近有点忙呢，不好意思哈。

**Comment by coolhorsema** [comment]
多谢，PullToRefreshLayout一直没有实现，把，ListView换成RecyclerView, 把PullToRefreshLayout换成PullToRefreshRecyclerView实现了上拉刷新，下拉加载功能



祝好！
-------------------------
coolhorsema@foxmail.com
 
发件人： Zhe Zhu
发送时间： 2017-11-20 23:35
收件人： baiiu/DropDownMenu
抄送： HowardMa; Mention
主题： Re: [baiiu/DropDownMenu] 请问下面的如果是个ListView如何实现下拉刷新或者上拉加载呢？ (#27)
@coolhorsema 恩，刚看到。
DropDownMenu是一个ViewGroup，里面可以包括任何东西。
Demo中包裹的是一个TextView，你可以直接修改Demo，将TextView改为PullToRefreshLayout试下，之后再将PullToRefreshLayout里改成ListView或RecyclerView。
最近有点忙呢，不好意思哈。

**Comment by baiiu** [comment]
恩，这样挺好。之后有时间会自己试下这块哈
