### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by RyanChouChina** [baiiu/DropDownMenu#28]
东西写的很好，逻辑也很清晰。但是已经好久没更新了，po主是不是没有继续做android了？   如果用recycleview替换调listview和gridview，然后加上gradle依赖，代码应该更简洁，功能更丰富。几千的star 应该很容易。。。哈哈哈

**Comment by baiiu** [comment]
恩，还在继续Android呢。
这个库主要封装的是筛选器那块，其他的都可以替换，所以自己实现吧~
