### ISSUE TITLE
必须点两次才能展示列表(可能是我自身问题)

### ISSUE THREAD

**Issue by is1988** [baiiu/DropDownMenu#34]
作者的项目我down下来运行没任何问题,然后移植到自己的项目中就有两个bug,我描述一下
1.点击第一栏下拉展示没问题,点击阴影合住没问题,再点第二栏阴影闪一下什么都没有,再次点击第二栏的选中消除,此时再点才会正常出现.
2.重复1的操作,最后一步切换到第三栏,此时会闪一下第二栏,然后再展示第三栏 不知道是为什么,还请大神赐教.

**Comment by is1988** [comment]
感觉是和我引的包或是第三方库有冲突 但又找不到是哪里

**Comment by baiiu** [comment]
恩，统一一下引用包的version看看
