### ISSUE TITLE
看了下实现是否支持扩展【顶部后吸附悬停】功能

### ISSUE THREAD

**Issue by NicodeLee** [baiiu/DropDownMenu#35]
顶部筛选条跟添加展开页面跟内容页封装在一起了
不好实现类似美团内容较多，【筛选条】滚动到顶部悬停吧。
作者是否考虑这个问题？能分享下扩展思路吗。

**Comment by baiiu** [comment]
第一个封装在一起了没听懂，现在这种已经分离了大部分了。

第二个，我可能会考虑看下TabLayout的源码，使用Behavior相关去实现。网上已经有这方面Demo，可以多参考下，这是个好需求。

**Comment by NicodeLee** [comment]
嗯，已经有思路了。还有个下拉有【重置、确定】的需求扩展。方便的话加个QQ：1058381138 咨询下你。

**Comment by NicodeLee** [comment]
上面的【重置、确定】没问题了，在BetterDoubleGridView的基础上，结合一个BaseAdapter库解决了。
使用代码大概是这个样子

BaseQuickAdapter adapter =
        new BaseQuickAdapter<String, BaseViewHolder>(R.layout.holder_item, list) {
          @Override
          protected void convert(BaseViewHolder helper, String item) {
            helper.setText(R.id.tv_item, item);
          }
        }; 
  

    adapter.setOnItemClickListener(
        (adapter1, view, position) -> {
          FilterUrl.instance().singleListPosition = list.get(position);
          FilterUrl.instance().position = 1;
          FilterUrl.instance().positionTitle = list.get(position);
          onFilterDone();
        });

    return new BetterListView(mContext)
        .setPosition(1)
        .setAdapter(adapter)
        .setOnFilterButtonListener(onFilterButtonListener)
        .build();
