### ISSUE TITLE
DoubleListView快速点击的时候

### ISSUE THREAD

**Issue by AADdAaaD** [baiiu/DropDownMenu#38]
当DoubleListView左侧条目快速点击的时候，会造成左侧和右侧条目在视图上对不上的情况，但是数据选择是没问题的，如选右侧115，左侧对应的数据是11

![_20180421092909](https://user-images.githubusercontent.com/16479283/39079097-aebb0db8-4546-11e8-87ed-61f93f49126a.png)

然后我把DoubleListView中onItemclick的重复判断去掉了，没这个问题了，但是这样可能会造成其他问题么？

**Comment by baiiu** [comment]
记得之前有人提过这个Issue，可以打Log排查下这块，欢迎提pr
