### ISSUE TITLE
请问如何定制singleGridView的样式呢？

### ISSUE THREAD

**Issue by defalt1996** [baiiu/DropDownMenu#42]
请问如何定制singleGridView下拉列表的样式呢？
例如定制成: 小学一栏下边有一年级、二年级、.....初中一栏下边有初一、初二、初三。这种有栏目的形式，依然为单选。
![img](https://user-images.githubusercontent.com/23403728/44970058-73e81900-af82-11e8-8ec5-3010016905c5.png)

**Comment by baiiu** [comment]
这种得自己写了，sample里有个RecyclerView实现的类似的，可以参考
