### ISSUE TITLE
动态添加网络数据

### ISSUE THREAD

**Issue by JamesLiAndroid** [baiiu/DropDownMenu#46]
如果我需要从后端获取数据，然后添加到DropDownMenuAdapter中，该如何操作？

我尝试了多次添加adapter，这样会出现异常！

**Comment by baiiu** [comment]
添加到list里，adapter.notify这样

**Comment by mingmingacc** [comment]
@JamesLiAndroid 您问您解决了吗

**Comment by JamesLiAndroid** [comment]
@mingmingacc 解决了，多个接口情况下，数据组织整合多次，但是只添加一次adapter，这样就可用了

**Comment by mingmingacc** [comment]
@JamesLiAndroid 
![1556501183(1)](https://user-images.githubusercontent.com/22333648/56872927-ee5d3000-6a60-11e9-9832-eb6c82501b49.png)
我的需求是点击上面的tab就刷新下面的筛选，不知道怎么搞了

**Comment by JamesLiAndroid** [comment]
@mingmingacc 这个是一样的，你获取删选条件组织好数据后，一次加载到adapter中就行
