### ISSUE TITLE
如何动态改变筛选分类的数据

### ISSUE THREAD

**Issue by mingmingacc** [baiiu/DropDownMenu#48]
![_EUY_C9Z1RPBERM7AXZWFD3](https://user-images.githubusercontent.com/22333648/56860176-ff0c9800-69c5-11e9-9acd-775daa4032a8.png)
我看基本都是这样写的，getView只会赋值一次，请问怎么改变呢

**Comment by baiiu** [comment]
@mingmingacc 改代码，获取view实例添加方法操作
