### ISSUE TITLE
菜单项可以重复点击

### ISSUE THREAD

**Issue by DemoJameson** [baiiu/DropDownMenu#5]
因为动画执行完之后才会将菜单项设置为 GONE，所以在动画执行完前可以不停点击

**Comment by baiiu** [comment]
@DemoJameson 
因为动画的延迟，所以会造成多次点击。和RxJava中对点击事件去重一样，添加了FastDoubleClick()方法进行去重，不允许在很短事件内响应多次点击事件。

谢谢你的细心。
