### ISSUE TITLE
读后感😄

### ISSUE THREAD

**Issue by wpq2014** [baiiu/DropDownMenu#6]
今天把这个项目基本都看了一遍，对比百度美团饿了么之类的团购、外卖APP，感觉这个写得真好！反正我是写不出来😂   看完写点读后感：1. butterknife如果能去掉就好了，如果项目里已经有另一个版本的butterknife了就不太合适了；2. 第四个DoubleGrid感觉可以改造的更灵活点，建议看看美团外卖的筛选。    再加一句，这么好的作品为毛才这点star啊fuck！感觉需要好好做做营销工作~

**Comment by baiiu** [comment]
@wpq2014 哈哈，谢谢~ ButterKnife、第四个DoubleGridView全都在Project里面，不再lib里面，如果想用直接拿lib去用就OK了。
start这么多已经很满足啦，之前只有10几个，都继续努力，写出更好的控件来。

**Comment by Fritz-Xu** [comment]
作者有blog吗？这个项目做的真好,起码比我做的同样功能的筛选器要强很多

**Comment by baiiu** [comment]
@Fritz-Xu 有个，在CSDN上。 [CSDN-baiiu](http://blog.csdn.net/u014099894)，多谢访问，持续学习啦。

**Comment by Fritz-Xu** [comment]
恩
