### ISSUE TITLE
为什么不加入gradle dependencies里面呢？

### ISSUE THREAD

**Issue by malkavia** [baiiu/DropDownMenu#7]
强迫症表示不需要做修改的依赖不想以Module的形式引入
如果可以直接compile的话就更好了：）

**Comment by baiiu** [comment]
因为对于每个条目的配置这块感觉处理的不是很好，现在是在adapter中提供了空实现可复写来修改Item的UI。
而且各家公司对于筛选器的设置不一样，所以直接修改源码而不是在外层修修补补这样岂不是更方便😁。
