### ISSUE TITLE
求教去修改筛选条件的字体颜色和大小

### ISSUE THREAD

**Issue by sunandy3** [baiiu/DropDownMenu#8]
求教去修改筛选条件的字体颜色和大小

**Comment by baiiu** [comment]
@sunandy3 
在Item的textColor属性里，是个selector。

**Comment by sunandy3** [comment]
如果是用gradle制定dependency

**Comment by baiiu** [comment]
@sunandy3 
嗯，在设置Adapter时回调出来了一个initCheckedTextView(FilterCheckedTextView)方法，复写该方法可以调整UI。

对UI的配置调整这块应该有更好的配置方式，之后想到了再做一次修改。
